package com.it.cloud.dao.teacher;

import com.it.cloud.domain.entity.teacher.Info;
import java.util.List;

public interface InfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbg.generated Wed Sep 04 22:37:40 CST 2019
     */
    int insert(Info record);

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbg.generated Wed Sep 04 22:37:40 CST 2019
     */
    List<Info> selectAll();
}