package com.it.cloud.domain.entity.teacher;

import java.io.Serializable;
import lombok.Data;

/**
 * Table: info
 */
@Data
public class Info implements Serializable {
    /**
     * Table:     info
     * Column:    id
     * Nullable:  true
     */
    private Integer id;

    /**
     * Table:     info
     * Column:    name
     * Nullable:  true
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table info
     *
     * @mbg.generated Wed Sep 04 22:37:40 CST 2019
     */
    private static final long serialVersionUID = 1L;
}